"""Hash-chain spec pins, chaining, tamper detection, and golden vectors.

The golden vectors in ``tests/fixtures/integrity_golden.json`` were
generated by an independent pre-extraction implementation of the same
spec; matching them proves the port is byte-compatible, and matching the
committed Ed25519 signature proves cross-implementation determinism.
"""

from __future__ import annotations

import dataclasses
import json
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

import pytest

from briefcase.integrity import (
    GENESIS_PRIOR_HASH,
    HashChainAppender,
    HashChainEntry,
    HashChainStore,
    InMemoryHashChainStore,
    compute_entry_hash,
    compute_payload_hash,
    verify_chain_segment,
)

GOLDEN = json.loads(
    (Path(__file__).parent.parent / "fixtures" / "integrity_golden.json").read_text()
)["chain"]


def _ts(n: int) -> datetime:
    return datetime(2026, 1, 1, 0, 0, n % 60, (n * 1000) % 1_000_000, tzinfo=timezone.utc)


def test_golden_payload_and_entry_hash() -> None:
    assert compute_payload_hash(GOLDEN["payload"]) == GOLDEN["payload_hash"]
    e = GOLDEN["entry"]
    assert (
        compute_entry_hash(
            row_id=e["row_id"],
            table=e["table"],
            entity_id=e["entity_id"],
            observed_at=datetime.fromisoformat(e["observed_at"]),
            recorded_at=datetime.fromisoformat(e["recorded_at"]),
            payload_hash=GOLDEN["payload_hash"],
            supersedes=e["supersedes"],
            prior_hash=GENESIS_PRIOR_HASH,
        )
        == GOLDEN["entry_hash"]
    )


def test_golden_signature_is_reproduced() -> None:
    pytest.importorskip("nacl")
    from briefcase.integrity.chain import _sign_hash

    seed = bytes.fromhex(GOLDEN["signature_seed_hex"])
    assert _sign_hash(seed, GOLDEN["entry_hash"]) == GOLDEN["signature_b64url"]


def test_genesis_entry_is_deterministic() -> None:
    payload_hash = compute_payload_hash({"a": 1, "b": "two"})
    kwargs = dict(
        row_id="01234567-89ab-7def-8000-000000000001",
        table="findings",
        entity_id="entity-1",
        observed_at=_ts(0),
        recorded_at=_ts(1),
        payload_hash=payload_hash,
        supersedes=None,
        prior_hash=GENESIS_PRIOR_HASH,
    )
    hash1 = compute_entry_hash(**kwargs)
    hash2 = compute_entry_hash(**kwargs)
    assert hash1 == hash2
    assert len(hash1) == 64 and all(c in "0123456789abcdef" for c in hash1)
    assert GENESIS_PRIOR_HASH == "0" * 64


def test_two_entry_chain_links_prior_hash() -> None:
    store = InMemoryHashChainStore()
    appender = HashChainAppender(store)

    entry1 = appender.append_row(
        table="findings",
        row_id=str(uuid.uuid4()),
        entity_id="entity-A",
        observed_at=_ts(0),
        recorded_at=_ts(1),
        payload={"severity": "high"},
    )
    entry2 = appender.append_row(
        table="findings",
        row_id=str(uuid.uuid4()),
        entity_id="entity-A",
        observed_at=_ts(2),
        recorded_at=_ts(3),
        payload={"severity": "critical"},
        supersedes=entry1.row_id,
    )

    assert entry1.prior_hash == GENESIS_PRIOR_HASH
    assert entry2.prior_hash == entry1.hash
    assert entry2.supersedes == entry1.row_id
    assert verify_chain_segment([entry1, entry2]) == (True, None)


def test_tampered_payload_hash_is_flagged_on_the_exact_row() -> None:
    store = InMemoryHashChainStore()
    appender = HashChainAppender(store)
    entries = [
        appender.append_row(
            table="findings",
            row_id=str(uuid.uuid4()),
            entity_id="entity-T",
            observed_at=_ts(10 + i),
            recorded_at=_ts(11 + i),
            payload={"k": "v%d" % i},
        )
        for i in range(3)
    ]
    tampered = dataclasses.replace(entries[1], payload_hash="ff" * 32)
    ok, failing = verify_chain_segment([entries[0], tampered, entries[2]])
    assert ok is False
    assert failing == tampered.row_id


def test_mid_chain_window_verifies_with_expected_prior() -> None:
    store = InMemoryHashChainStore()
    appender = HashChainAppender(store)
    entries = [
        appender.append_row(
            table="findings",
            row_id=str(uuid.uuid4()),
            entity_id="entity-W",
            observed_at=_ts(i),
            recorded_at=_ts(i + 1),
            payload={"i": i},
        )
        for i in range(5)
    ]
    window = entries[2:]
    # Default genesis expectation rejects a slice that starts mid-chain...
    ok, failing = verify_chain_segment(window)
    assert ok is False and failing == window[0].row_id
    # ...and the hash preceding the window accepts it.
    assert verify_chain_segment(window, expected_prior=entries[1].hash) == (True, None)


def test_canonical_payload_hash_is_key_order_independent() -> None:
    forward = {"alpha": 1, "beta": 2, "gamma": {"x": 10, "y": 20}}
    reordered = {"gamma": {"y": 20, "x": 10}, "beta": 2, "alpha": 1}
    assert compute_payload_hash(forward) == compute_payload_hash(reordered)


def test_naive_and_aware_utc_datetimes_hash_identically() -> None:
    aware = datetime(2026, 5, 17, 12, 34, 56, 789012, tzinfo=timezone.utc)
    naive = aware.replace(tzinfo=None)
    common = dict(
        row_id="01234567-89ab-7def-8000-000000000003",
        table="t",
        entity_id="e",
        payload_hash=compute_payload_hash({"x": 1}),
        supersedes=None,
        prior_hash=GENESIS_PRIOR_HASH,
    )
    assert compute_entry_hash(observed_at=aware, recorded_at=aware, **common) == compute_entry_hash(
        observed_at=naive, recorded_at=naive, **common
    )


def test_appender_signs_entries_when_given_a_seed() -> None:
    pytest.importorskip("nacl")
    store = InMemoryHashChainStore()
    appender = HashChainAppender(store, signing_key=b"\x01" * 32)
    entry = appender.append_row(
        table="findings",
        row_id=str(uuid.uuid4()),
        entity_id="entity-sig",
        observed_at=_ts(0),
        recorded_at=_ts(1),
        payload={"signed": True},
    )
    assert entry.signature is not None
    # base64url-nopad Ed25519 signature over 32 bytes is 86 chars.
    assert len(entry.signature) == 86


def test_thousand_entry_chain_verifies_quickly() -> None:
    store = InMemoryHashChainStore()
    appender = HashChainAppender(store)
    prior_row_id = None
    for i in range(1000):
        entry = appender.append_row(
            table="findings",
            row_id=str(uuid.uuid4()),
            entity_id="entity-1k",
            observed_at=_ts(i),
            recorded_at=_ts(i + 1),
            payload={"i": i, "marker": "x" * 32},
            supersedes=prior_row_id,
        )
        prior_row_id = entry.row_id
    entries = store.all_entries()
    assert len(entries) == 1000
    start = time.perf_counter()
    assert verify_chain_segment(entries) == (True, None)
    assert time.perf_counter() - start < 2.0


def test_in_memory_store_satisfies_the_protocol() -> None:
    assert isinstance(InMemoryHashChainStore(), HashChainStore)


def test_entry_is_immutable() -> None:
    entry = HashChainEntry(
        row_id="r",
        table="t",
        entity_id=None,
        observed_at=_ts(0),
        recorded_at=_ts(1),
        payload_hash="00" * 32,
        supersedes=None,
        prior_hash=GENESIS_PRIOR_HASH,
        hash="11" * 32,
    )
    with pytest.raises(dataclasses.FrozenInstanceError):
        entry.hash = "22" * 32  # type: ignore[misc]
