/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Prices model invocations from the built-in table of first-party and
 * Bedrock list rates.
 */
export declare class CostCalculator {
  constructor()
  /**
   * Estimates the cost of one invocation. Unknown models reject with an
   * error naming the id; platform-qualified ids normalize automatically.
   */
  estimateCost(modelName: string, inputTokens: number, outputTokens: number): CostEstimate
  /** Lists every registered pricing-table model id. */
  modelIds(): Array<string>
}

/** Cost estimate for one model invocation, in USD. */
export interface CostEstimate {
  modelName: string
  inputTokens: number
  outputTokens: number
  inputCost: number
  outputCost: number
  totalCost: number
}

/**
 * Canonicalizes a platform-qualified model id (region and vendor prefixes,
 * date stamps, version suffixes) to a pricing-table key. Cost estimation
 * applies this automatically when the exact id is not registered.
 */
export declare function normalizeModelId(modelId: string): string
